all: invirtiendo_fichero append insertar2x

invirtiendo_fichero: invirtiendo_fichero.c
	gcc -o invirtiendo_fichero invirtiendo_fichero.c

append: append.c
	gcc -o append append.c

insertar2x: insertar2x.c
	gcc -o insertar2x insertar2x.c

clean: 
	rm append invirtiendo_fichero insertar2x
